version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  
  postgres-user:
    container_name: postgres-user
    image: postgres:latest
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    environment:
      POSTGRES_DB: wedding-app-users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dondot3056
      PGDATA: /data/postgres
    volumes:
      - ./local-data-user:/var/lib/postgresql/data
      - ./config/user-data.sql:/docker-entrypoint-initdb.d/user-data.sql:ro
    ports:
      - "5432:5432"
    restart: unless-stopped

  postgres-wedding:
    container_name: postgres-wedding
    image: postgres:latest
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    environment:
      POSTGRES_DB: weddings
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dondot3056
      PGDATA: /data/postgres
    volumes:
      - ./local-data-wedding:/var/lib/postgresql/data
      - ./config/wedding-data.sql:/docker-entrypoint-initdb.d/wedding-data.sql:ro
    ports:
      - "5431:5432"
    restart: unless-stopped

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    restart: unless-stopped

  mailhog:
      image: davidtega/mailhog
      container_name: mailhog
      ports:
        - "1025:1025"
        - "8025:8025"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - postgres-user
      - postgres-wedding
    restart: unless-stopped

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    volumes:
      - ./jenkins:/var/jenkins_home
    environment:
      JENKINS_HOST_HOME: "/jenkins"
    ports:
      - '8080:8080'
      - '50000:50000'