global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8082']
        labels:
          application: 'User Service Application'
  
  - job_name: 'discovery-service'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8761']
        labels:
          application: 'Discovery Service Application'
    
  - job_name: 'api-gateway'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8000'] 
        labels:
          application: 'API Gateway Application'

  - job_name: 'mail-service'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:9091'] 
        labels:
          application: 'Mail Service Application'